export enum AuthActions {
	SET_AUTH_STATUS = 'SET_AUTH_STATUS'
}

export enum PlanetActions {
	ADD_PLANET_TO_FAVOURITES = 'ADD_PLANET_TO_FAVOURITES',
	ADD_PLANETS = 'ADD_PLANETS',
	REMOVE_PLANET_FROM_FAVOURITES = 'REMOVE_PLANET_FROM_FAVOURITES'
}
